modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "BSD 3-Clause (NewBSD) License"

[[mods]]
modId = "ubercord"
version = "${version}"
displayName = "ubercord"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.ubercord]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ubercord]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ubercord]]
modId = "cloth-config"
type = "optional"
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ubercord]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ubercord.mixins.json"
